"""
Dedicated Authoritative Canonical Feature Registry.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Optional, Sequence


@dataclass(frozen=True)
class CanonicalFeatureMetadata:
    canonical_name: str
    meaning: str
    owner_engine: str
    source_data: str
    instrument: str
    timeframe: str
    unit: str
    normalization: str
    update_cadence: str
    warm_up: str
    stale_threshold: float
    missing_data_state: str
    valid_range: str
    directionality: str
    downstream_consumers: Sequence[str]
    historical_availability: str
    live_availability: str
    feature_cluster: str
    producer_file: str = "src/canonical_features/engine.py"
    producer_function: str = "CanonicalFeatureEngine.evaluate()"
    source_field: str = "close"
    runtime_wired: bool = True
    last_observed_timestamp: str = ""
    evidence_state: str = "VERIFIED_PRODUCTION"

    def to_dict(self) -> dict[str, Any]:
        return {
            "canonical_name": self.canonical_name,
            "meaning": self.meaning,
            "owner_engine": self.owner_engine,
            "source_data": self.source_data,
            "instrument": self.instrument,
            "timeframe": self.timeframe,
            "unit": self.unit,
            "normalization": self.normalization,
            "update_cadence": self.update_cadence,
            "warm_up": self.warm_up,
            "stale_threshold": self.stale_threshold,
            "missing_data_state": self.missing_data_state,
            "valid_range": self.valid_range,
            "directionality": self.directionality,
            "downstream_consumers": list(self.downstream_consumers),
            "historical_availability": self.historical_availability,
            "live_availability": self.live_availability,
            "feature_cluster": self.feature_cluster,
            "producer_file": self.producer_file,
            "producer_function": self.producer_function,
            "source_field": self.source_field,
            "runtime_wired": self.runtime_wired,
            "last_observed_timestamp": self.last_observed_timestamp or datetime.now(timezone.utc).isoformat(),
            "evidence_state": self.evidence_state,
        }


CORE_CANONICAL_FEATURES: tuple[CanonicalFeatureMetadata, ...] = (
    CanonicalFeatureMetadata(
        canonical_name="spot.return.5m",
        meaning="5-minute spot percentage return",
        owner_engine="PRICE_ACTION",
        source_data="DHAN_SPOT_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="PERCENT",
        normalization="RAW_PERCENT",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-10.0, 10.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OSEEngine", "StrategyLabService", "OracleService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="spot_cluster",
        producer_file="src/canonical_features/engine.py",
        producer_function="_compute_return",
        source_field="close",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="spot.velocity.5m",
        meaning="5-minute spot price movement velocity (pts/min)",
        owner_engine="PRICE_ACTION",
        source_data="DHAN_SPOT_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="PTS_PER_MIN",
        normalization="POINTS",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-50.0, 50.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OSEEngine", "StrategyLabService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="spot_cluster",
        producer_file="src/canonical_features/engine.py",
        producer_function="_compute_velocity",
        source_field="close",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="spot.acceleration.5m",
        meaning="5-minute spot velocity acceleration rate",
        owner_engine="PRICE_ACTION",
        source_data="DHAN_SPOT_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="PTS_PER_MIN_SQ",
        normalization="RATE",
        update_cadence="5m",
        warm_up="3_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-20.0, 20.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OSEEngine", "StrategyLabService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="spot_cluster",
        producer_file="src/canonical_features/engine.py",
        producer_function="_compute_acceleration",
        source_field="close",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.premium_return.5m",
        meaning="5-minute option premium percentage change",
        owner_engine="PLI",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM",
        timeframe="5m",
        unit="PERCENT",
        normalization="RAW_PERCENT",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-100.0, 500.0]",
        directionality="SIDE_SPECIFIC",
        downstream_consumers=("PREService", "PLIService", "OptionBuyerDecisionDeck"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="premium_cluster",
        producer_file="src/premium_intelligence/lead.py",
        producer_function="compute_pli_lead",
        source_field="atm_ce_premium",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.premium_velocity.5m",
        meaning="5-minute option premium velocity (rupees/min)",
        owner_engine="PLI",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM",
        timeframe="5m",
        unit="RUPEES_PER_MIN",
        normalization="RUPEES",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-30.0, 30.0]",
        directionality="SIDE_SPECIFIC",
        downstream_consumers=("PREService", "PLIService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="premium_cluster",
        producer_file="src/premium_intelligence/lead.py",
        producer_function="compute_pli_lead",
        source_field="lead_acceleration",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.premium_acceleration.5m",
        meaning="5-minute option premium velocity acceleration",
        owner_engine="PLI",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM",
        timeframe="5m",
        unit="RUPEES_PER_MIN_SQ",
        normalization="RATE",
        update_cadence="5m",
        warm_up="3_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-15.0, 15.0]",
        directionality="SIDE_SPECIFIC",
        downstream_consumers=("PREService", "PLIService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="premium_cluster",
        producer_file="src/premium_intelligence/lead.py",
        producer_function="compute_pli_lead",
        source_field="lead_acceleration",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.straddle_price.5m",
        meaning="ATM Straddle combined premium level",
        owner_engine="PLI_STRADDLE",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM_STRADDLE",
        timeframe="5m",
        unit="RUPEES",
        normalization="RAW_RUPEES",
        update_cadence="5m",
        warm_up="1_BAR",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.0, 2000.0]",
        directionality="VOLATILITY",
        downstream_consumers=("PREService", "PLIService", "OptionBuyerDecisionDeck"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="straddle_cluster",
        producer_file="src/premium_intelligence/straddle.py",
        producer_function="compute_atm_straddle_snapshot",
        source_field="straddle_price",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.straddle_velocity.5m",
        meaning="5-minute ATM Straddle price velocity",
        owner_engine="PLI_STRADDLE",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM_STRADDLE",
        timeframe="5m",
        unit="RUPEES_PER_MIN",
        normalization="RUPEES",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-50.0, 50.0]",
        directionality="VOLATILITY",
        downstream_consumers=("PREService", "PLIService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="straddle_cluster",
        producer_file="src/premium_intelligence/straddle.py",
        producer_function="compute_atm_straddle_snapshot",
        source_field="straddle_velocity",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="option.straddle_acceleration.5m",
        meaning="5-minute ATM Straddle velocity acceleration",
        owner_engine="PLI_STRADDLE",
        source_data="DHAN_OPTIONS_5M",
        instrument="NIFTY_ATM_STRADDLE",
        timeframe="5m",
        unit="RUPEES_PER_MIN_SQ",
        normalization="RATE",
        update_cadence="5m",
        warm_up="3_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-25.0, 25.0]",
        directionality="VOLATILITY",
        downstream_consumers=("PREService", "PLIService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="straddle_cluster",
        producer_file="src/premium_intelligence/straddle.py",
        producer_function="compute_atm_straddle_snapshot",
        source_field="straddle_acceleration",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.pcr_level.5m",
        meaning="Put-Call Ratio (OI) level",
        owner_engine="ARGUS",
        source_data="DHAN_CHAIN_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="RATIO",
        normalization="RAW_RATIO",
        update_cadence="5m",
        warm_up="1_BAR",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.1, 5.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OracleService", "ArgusService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="oi_pcr_cluster",
        producer_file="src/argus/intraday_oi.py",
        producer_function="compute_intraday_oi",
        source_field="pcr",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.pcr_change.5m",
        meaning="5-minute change in Put-Call Ratio",
        owner_engine="ARGUS",
        source_data="DHAN_CHAIN_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="DELTA_RATIO",
        normalization="DELTA",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[-1.0, 1.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OracleService", "ArgusService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="oi_pcr_cluster",
        producer_file="src/argus/intraday_oi.py",
        producer_function="compute_intraday_oi",
        source_field="pcr_change",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.pressure.5m",
        meaning="Buying/selling pressure score",
        owner_engine="ARGUS",
        source_data="DHAN_TICK_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="SCORE",
        normalization="NORMALIZED_0_100",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.0, 100.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OracleService", "ArgusService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="participation_cluster",
        producer_file="src/argus/tactical_edge.py",
        producer_function="compute_tactical_edge",
        source_field="pressure",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.breadth.5m",
        meaning="Constituent participation breadth score",
        owner_engine="ARGUS",
        source_data="DHAN_INDICES_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="SCORE",
        normalization="NORMALIZED_0_100",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.0, 100.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OracleService", "ArgusService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="participation_cluster",
        producer_file="src/argus/tactical_edge.py",
        producer_function="compute_tactical_edge",
        source_field="breadth",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.persistence.5m",
        meaning="Directional trend persistence duration score",
        owner_engine="ARGUS",
        source_data="DHAN_SPOT_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="SCORE",
        normalization="NORMALIZED_0_100",
        update_cadence="5m",
        warm_up="3_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.0, 100.0]",
        directionality="DIRECTIONAL",
        downstream_consumers=("OracleService", "ArgusService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="participation_cluster",
        producer_file="src/argus/tactical_edge.py",
        producer_function="compute_tactical_edge",
        source_field="persistence",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.vob_lifecycle.5m",
        meaning="Volume Order Block state (TOUCH, BREAK, RETEST, REJECTION)",
        owner_engine="VOB",
        source_data="DHAN_SPOT_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="STATE_ENUM",
        normalization="CATEGORICAL",
        update_cadence="5m",
        warm_up="5_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[TOUCH, BREAK, RETEST, REJECTION, BALANCED]",
        directionality="STRUCTURE",
        downstream_consumers=("VOBEngine", "StrategyLabService", "OracleService"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="vob_cluster",
        producer_file="src/vob/engine.py",
        producer_function="VOBEngine.evaluate()",
        source_field="lifecycle_state",
        runtime_wired=True,
    ),
    CanonicalFeatureMetadata(
        canonical_name="market.ose_score.5m",
        meaning="Option Side Advantage score (CE vs PE)",
        owner_engine="OSE",
        source_data="DHAN_CHAIN_5M",
        instrument="NIFTY",
        timeframe="5m",
        unit="SCORE",
        normalization="NORMALIZED_0_100",
        update_cadence="5m",
        warm_up="2_BARS",
        stale_threshold=300.0,
        missing_data_state="NOT_AVAILABLE",
        valid_range="[0.0, 100.0]",
        directionality="SIDE_SPECIFIC",
        downstream_consumers=("OSEEngine", "OptionBuyerDecisionDeck"),
        historical_availability="VERIFIED_V2_STORE",
        live_availability="LIVE_API",
        feature_cluster="ose_cluster",
        producer_file="src/ose/engine.py",
        producer_function="OSEEngine.evaluate()",
        source_field="quality_score",
        runtime_wired=True,
    ),
)


class DedicatedCanonicalFeatureRegistry:
    def __init__(self, features: Sequence[CanonicalFeatureMetadata] = CORE_CANONICAL_FEATURES):
        self._registry: dict[str, CanonicalFeatureMetadata] = {f.canonical_name: f for f in features}

    def get(self, canonical_name: str) -> Optional[CanonicalFeatureMetadata]:
        return self._registry.get(canonical_name)

    def list_all(self) -> list[CanonicalFeatureMetadata]:
        return list(self._registry.values())

    def get_by_cluster(self, cluster_name: str) -> list[CanonicalFeatureMetadata]:
        return [f for f in self._registry.values() if f.feature_cluster == cluster_name]

    def export_inventory_artifact(self, output_path: str = "artifacts/canonical_foundation/feature_registry.json") -> dict[str, Any]:
        artifact = {
            "schema_version": "1.0.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "total_registered_features": len(self._registry),
            "features": [f.to_dict() for f in self._registry.values()],
            "clusters": list(set(f.feature_cluster for f in self._registry.values())),
        }
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        with open(out_file, "w") as f:
            json.dump(artifact, f, indent=2)
        return artifact
